### ISSUE TITLE
Package name is innacurate

### ISSUE THREAD

**Issue by ofrank123** [GDQuest/emacs-gdscript-flycheck#1]
The package name `flycheck-gdscript` implies that this package provides general flycheck support for GDScript, when it only provides the functionality available in `gdlint`.  Perhaps we should change the name to `flycheck-gdlint`?

**Comment by NathanLovato** [comment]
Most flycheck extensions for a given language seem to use external tools (e.g. for python, pylint and flake8).

There's no other tool than gdlint we can use to parse and check for errors right now. But to me the goal is to generally support GDScript, and the quality of the package will increase over time, as the tools mature.

Inside a given flycheck extension, you can have multiple checkers, so we can also extend the package later. 

In any case, I think naming any gdscript-related package `*-gdlint` would only make it harder to find and less clear than `*-gdscript`.

**Comment by ofrank123** [comment]
Ok, sounds good.
