### ISSUE TITLE
missing the script

### ISSUE THREAD

**Issue by ginobean** [GDQuest/emacs-gdscript-flycheck#2]
I cloned this repo but it seems to be missing the actual gdscript-flycheck.el script.

Can you guys check in this script?

**Comment by NathanLovato** [comment]
@ofrank123 has written it as a PR of our other repo but not pushed here yet. Oliver, when you have the time, could you add the package here? You can clone and write to this repo directly.

**Comment by ofrank123** [comment]
Yes

**Comment by Samdal** [comment]
any update on this @ofrank123 ?

**Comment by NathanLovato** [comment]
The language server client handles errors through flycheck, so we won't add an extra package. I'll archive this repository.
